/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import jakarta.validation.Valid;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "comments", description = "Универсальный сервис для работы с комментариями")
public interface CommentsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /comments : Создать новый комментарий
     *
     * @param commentData Данные комментария в виде Map (required)
     * @return Комментарий успешно создан (status code 201)
     *         or Неверный формат данных (status code 400)
     */
    @Operation(
            operationId = "createComment",
            summary = "Создать новый комментарий",
            responses = {
                    @ApiResponse(responseCode = "201", description = "Комментарий успешно создан"),
                    @ApiResponse(responseCode = "400", description = "Неверный формат данных")
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/comments",
            consumes = { "application/json" }
    )
    default ResponseEntity<Void> createComment(
            @Parameter(description = "Данные комментария", required = true)
            @Valid @RequestBody Map<String, Object> commentData
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

    /**
     * GET /comments : Получить все комментарии
     *
     * @param parentId ID родительского элемента (optional)
     * @return Список комментариев успешно получен (status code 200)
     */
    @Operation(
            operationId = "getAllComments",
            summary = "Получить все комментарии",
            responses = {
                    @ApiResponse(
                            responseCode = "200",
                            description = "Список комментариев успешно получен",
                            content = @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(type = "array", implementation = Map.class)
                            )
                    )
            }
    )
    @GetMapping(value = "/comments", produces = MediaType.APPLICATION_JSON_VALUE)
    default ResponseEntity<List<Map<String, Object>>> getAllComments(
            @Parameter(description = "ID родительского элемента", in = ParameterIn.QUERY)
            @RequestParam(value = "parentId", required = false) String parentId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

    /**
     * GET /comments/{id} : Получить комментарий по ID
     *
     * @param id ID комментария (required)
     * @return Комментарий успешно получен (status code 200)
     *         or Комментарий не найден (status code 404)
     */
    @Operation(
            operationId = "getCommentById",
            summary = "Получить комментарий по ID",
            responses = {
                    @ApiResponse(
                            responseCode = "200",
                            description = "Комментарий успешно получен",
                            content = @Content(mediaType = "application/json",
                                    schema = @Schema(implementation = Map.class))),
                    @ApiResponse(responseCode = "404", description = "Комментарий не найден")
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/comments/{id}",
            produces = { "application/json" }
    )
    default ResponseEntity<Map<String, Object>> getCommentById(
            @Parameter(description = "ID комментария", required = true, in = ParameterIn.PATH)
            @PathVariable("id") String id
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

    /**
     * DELETE /comments/{id} : Удалить комментарий
     *
     * @param id ID комментария (required)
     * @return Комментарий успешно удален (status code 204)
     *         or Комментарий не найден (status code 404)
     */
    @Operation(
            operationId = "deleteComment",
            summary = "Удалить комментарий",
            responses = {
                    @ApiResponse(responseCode = "204", description = "Комментарий успешно удален"),
                    @ApiResponse(responseCode = "404", description = "Комментарий не найден")
            }
    )
    @RequestMapping(
            method = RequestMethod.DELETE,
            value = "/comments/{id}"
    )
    default ResponseEntity<Void> deleteComment(
            @Parameter(description = "ID комментария", required = true, in = ParameterIn.PATH)
            @PathVariable("id") String id
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }
}